name: 'Download Dockerfile'
description: 'Dowload the Dockerfile from the repository'
inputs:
  exec-method:
    description: 'Execution method to use'
    required: true
    default: 'default'
  ikusi-token:
    description: 'Ikusi PAT token to checkout the repository'
    required: true
    default: ''

defaults:
  run:
    shell: bash

runs:
  using: "composite"
  steps:
    - name: debug secrets
      run: |
        echo "IKSUI_PAT is set to ${{ inputs.ikusi-token }}"

    - name: checkout dockerfile from templates repository
      if: ${{inputs.exec-method == 'uvicorn'}}
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.ikusi-token }}
        repository: 'ikusi-id-lite/devops-resources'
        ref: 'main'
        path: dockerfile
        sparse-checkout: |
          dockerfiles/python/uvicorn-expose/Dockerfile
        sparse-checkout-cone-mode: false

    - name: Copying Dockerfile
      shell: bash
      run: cp ./dockerfile/dockerfiles/python/uvicorn-expose/Dockerfile ./Dockerfile