name: 'Build and Push Image'
description: 'Build and push the Docker image to the registry'
inputs:
  registry_project:
    description: 'Registry project name'
    required: true
    default: 'test-devops'
  registry_repository:
    description: 'Registry repository name'
    required: true
    default: 'python-artifact'
  harbor-token:
    description: 'Harbor robot account token'
    required: true
    default: ''

runs:
  using: "composite"
  steps:

    #- name: Build and push
    #  id: build_and_push_to_harbor
    #  shell: bash
    #  run: |
    #    AUTH=$(echo -n robot\$ikusigh:${{ inputs.harbor-token }} | base64)
    #    cat << EOF > config.json
    #    {
    #      "auths":{
    #        "192.168.50.127:30002/${{ inputs.registry_project }}/${{ inputs.registry_repository }}":{
    #          "username":"robot\$ikusigh","password":"${{ inputs.harbor-token }}","auth":"${AUTH}"
    #        }
    #      }
    #    }
    #    EOF
    #    docker run \
    #      -v $(pwd):/workspace \
    #      -v $(pwd)/config.json:/kaniko/.docker/config.json:ro \
    #      gcr.io/kaniko-project/executor:latest \
    #        --context . \
    #        --destination 192.168.50.127:30002/${{ inputs.registry_project }}/${{ inputs.registry_repository }}:1


    - name: Prepare Kaniko Authentication
      shell: bash
      run: |
        # Creamos el directorio para el config.json de Docker
        mkdir -p ${{ github.workspace }}/kaniko_home/.docker
        
        # Generamos el AUTH en base64 (usuario robot$ikusigh)
        AUTH=$(echo -n "robot\$ikusigh:${{ inputs.harbor-token }}" | base64)
        
        # Escribimos el config.json apuntando a tu IP de Harbor
        cat << EOF > ${{ github.workspace }}/kaniko_home/.docker/config.json
        {
          "auths": {
            "192.168.50.127:30002": {
              "auth": "$AUTH"
            }
          }
        }
        EOF

    - name: Build and Push with Kaniko
      # Usamos la acción de Google que envuelve al ejecutor de Kaniko
      # Esta acción es un "Docker Container Action", lo que en ARC
      # lanza un contenedor separado, evitando el error de docker.sock
      uses: aes-at-google/kaniko-action@v1
      with:
        image: 192.168.50.127:30002/${{ inputs.registry_project }}/${{ inputs.registry_repository }}
        tag: 1
        # Pasamos la ruta del config.json que creamos arriba
        extra_args: >
          --insecure 
          --skip-tls-verify 
          --docker-config-json=${{ github.workspace }}/kaniko_home/.docker/config.json